            - name: Make OpenWrt using flippy's script
  # You may pin to the exact commit or the version.
  # uses: ophub/flippy-openwrt-actions@9230ac4f7568e7c1b1c2744af13cde494aa9b3ac
  uses: ophub/flippy-openwrt-actions@v0.1.0
  with:
    # Select script.
    mode: # optional, default is flippy
          
